UPDATE plants
SET
    days_to_germination = $2,
    days_to_harvest = $3,
    description = $4,
    determinate = $5,
    fall_start_indoors = $6,
    fall_start_outdoors = $7,
    fall_transplant = $8,
    family = $9,
    first_name = $10,
    germination_temps_f = $11,
    last_day_to_plant = $12,
    light = $13,
    perennial = $14,
    plant_spacing = $15,
    pruning = $16,
    row_spacing = $17,
    second_name = $18,
    seed_depth = $19,
    soil = $20,
    start_indoors = $21,
    start_outdoors = $22,
    transplant = $23,
    type = $24,
    water = $25,
    updated_at = $26
WHERE plants.id = $1