import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
    // Deletes ALL existing entries
    await knex('plants').del();

    // Inserts seed entries
    await knex('plants').insert([
        {
            author_id: null,
            common_name: 'Tomato',
            variety: 'Brandywine',
            scientific_name: 'Solanum lycopersicum',
            description: 'A popular warm-season fruiting vegetable.',
            plant_family_id: 11, // Solanaceae
            plant_type_id: 3,    // Fruit
            days_to_germination: 7,
            days_to_harvest: 75,
            indeterminate: true,
            germination_temp_high: 95,
            germination_temp_low: 60,
            light: 'Full Sun',
            water: 'Moderate',
            soil: 'Loamy',
            perennial: false,
            heirloom: true,
            hybrid: false,
            open_pollinated: true,
            self_pollinated: true,
            spacing: 24,
            row_spacing: 36,
            pruning: 'Remove suckers for better airflow.',
            sowing_depth: 0.25,
            deleted_at: null,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            author_id: null,
            common_name: 'Carrot',
            variety: 'Nantes',
            scientific_name: 'Daucus carota',
            description: 'A cool-season root vegetable.',
            plant_family_id: 2, // Apiaceae
            plant_type_id: 1,   // Root
            days_to_germination: 14,
            days_to_harvest: 70,
            indeterminate: false,
            germination_temp_high: 85,
            germination_temp_low: 45,
            light: 'Full Sun',
            water: 'Moderate',
            soil: 'Sandy Loam',
            perennial: false,
            heirloom: true,
            hybrid: false,
            open_pollinated: true,
            self_pollinated: false,
            spacing: 2,
            row_spacing: 12,
            pruning: '',
            sowing_depth: 0.25,
            deleted_at: null,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            author_id: null,
            common_name: 'Lettuce',
            variety: 'Butterhead',
            scientific_name: 'Lactuca sativa',
            description: 'A fast-growing leafy green for salads.',
            plant_family_id: 3, // Asteraceae
            plant_type_id: 2,   // Leafy Green
            days_to_germination: 7,
            days_to_harvest: 55,
            indeterminate: false,
            germination_temp_high: 75,
            germination_temp_low: 40,
            light: 'Full Sun/Partial Shade',
            water: 'Moderate',
            soil: 'Loamy',
            perennial: false,
            heirloom: true,
            hybrid: false,
            open_pollinated: true,
            self_pollinated: false,
            spacing: 8,
            row_spacing: 12,
            pruning: '',
            sowing_depth: 0.25,
            deleted_at: null,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            author_id: null,
            common_name: 'Green Bean',
            variety: 'Blue Lake',
            scientific_name: 'Phaseolus vulgaris',
            description: 'A warm-season legume grown for its edible pods.',
            plant_family_id: 6, // Fabaceae
            plant_type_id: 4,   // Legume
            days_to_germination: 8,
            days_to_harvest: 60,
            indeterminate: false,
            germination_temp_high: 90,
            germination_temp_low: 60,
            light: 'Full Sun',
            water: 'Moderate',
            soil: 'Loamy',
            perennial: false,
            heirloom: true,
            hybrid: false,
            open_pollinated: true,
            self_pollinated: true,
            spacing: 4,
            row_spacing: 18,
            pruning: '',
            sowing_depth: 1,
            deleted_at: null,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            author_id: null,
            common_name: 'Zucchini',
            variety: 'Black Beauty',
            scientific_name: 'Cucurbita pepo',
            description: 'A prolific summer squash.',
            plant_family_id: 5, // Cucurbitaceae
            plant_type_id: 3,   // Fruit
            days_to_germination: 7,
            days_to_harvest: 50,
            indeterminate: false,
            germination_temp_high: 95,
            germination_temp_low: 70,
            light: 'Full Sun',
            water: 'Moderate',
            soil: 'Loamy',
            perennial: false,
            heirloom: true,
            hybrid: false,
            open_pollinated: true,
            self_pollinated: false,
            spacing: 24,
            row_spacing: 36,
            pruning: '',
            sowing_depth: 1,
            deleted_at: null,
            created_at: new Date(),
            updated_at: new Date(),
        },
    ]);
}